# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 422ca05741124d3ba0df4d6378eba6356cf884e6886b777ea219a15856e14be464b5fb631d0637a8456addfc472676b9b28596ca398eefd50c90a8432bb4dc29

test:
  secret_key_base: 7aea9dd28a811194fb847832902986107abebd4c2bb415a8f5b01dfc63b4f0bf12fb2bd63216f71599161844d7bedac315451159bd3df8e1843a3298f4a7d17a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
